# Generated by Django 2.1.5 on 2020-06-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Years_of_experience',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
